In [1]:
options(jupyter.rich_display = FALSE)

# Assignment 1: R Basics and Control Flow

## POP77001 Computer Programming for Social Scientists

## Before submission

- Make sure that you can run all cells without errors
- You can do it by clicking `Kernel`, `Restart & Run All` in the menu above
- Make sure that you save the output by pressing Command+S / CTRL+S
- Rename the file from `01_assignment.ipynb` to `01_assignment_lastname_firstname_studentnumber.ipynb`
- Use Firefox browser for submitting your Jupyter notebook on Blackboard

## Exercise 1: Subsetting (20 points)

Write 3 separate subsetting operations to extract the following elements from the list below:
- All consonants from the first character vector
- Second columns in all dimensions from the array A
- Odd rows from the matrix M

In [2]:
l <- list(
    mapply(assign, letters, 1:26),
    A = array(1:60, c(5,2,3)),
    M = matrix(1:50, c(10,5))
)

In [3]:
l

[[1]]
 a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q  r  s  t  u  v  w  x  y  z 
 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

$A
, , 1

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

, , 2

     [,1] [,2]
[1,]   11   16
[2,]   12   17
[3,]   13   18
[4,]   14   19
[5,]   15   20

, , 3

     [,1] [,2]
[1,]   21   26
[2,]   22   27
[3,]   23   28
[4,]   24   29
[5,]   25   30


$M
      [,1] [,2] [,3] [,4] [,5]
 [1,]    1   11   21   31   41
 [2,]    2   12   22   32   42
 [3,]    3   13   23   33   43
 [4,]    4   14   24   34   44
 [5,]    5   15   25   35   45
 [6,]    6   16   26   36   46
 [7,]    7   17   27   37   47
 [8,]    8   18   28   38   48
 [9,]    9   19   29   39   49
[10,]   10   20   30   40   50


In [4]:
# Exercise 1:

# Your code goes here


1. All consonants from the first character vector

In [5]:
LETTERS <- l[[1]]
str(LETTERS)
CONSONANTS <- LETTERS[c("b", "c", "d", "f", "g", "h", "j", "k",
                        "l", "m", "n", "p", "q", "r", "s", 
                        "t", "v", "w", "x", "y", "z")]
CONSONANTS
str(CONSONANTS) ## 21 character vectors

 Named int [1:26] 1 2 3 4 5 6 7 8 9 10 ...
 - attr(*, "names")= chr [1:26] "a" "b" "c" "d" ...


 b  c  d  f  g  h  j  k  l  m  n  p  q  r  s  t  v  w  x  y  z 
 2  3  4  6  7  8 10 11 12 13 14 16 17 18 19 20 22 23 24 25 26 

 Named int [1:21] 2 3 4 6 7 8 10 11 12 13 ...
 - attr(*, "names")= chr [1:21] "b" "c" "d" "f" ...


2. Second columns in all dimensions from the array A

In [6]:
SDA <- l$A[, 2, ]

SDA

     [,1] [,2] [,3]
[1,]  6   16   26  
[2,]  7   17   27  
[3,]  8   18   28  
[4,]  9   19   29  
[5,] 10   20   30  

3. Odd rows from the matrix M

In [7]:
MC1 <- l$M
MC1

MROWS_ODD <- seq_len(nrow(MC1)) %% 2   

MROWS_ODD

MC1_ODDROWS <- MC1[MROWS_ODD == 1, ]    
MC1_ODDROWS # Odd rows from the Matrix M

      [,1] [,2] [,3] [,4] [,5]
 [1,]  1   11   21   31   41  
 [2,]  2   12   22   32   42  
 [3,]  3   13   23   33   43  
 [4,]  4   14   24   34   44  
 [5,]  5   15   25   35   45  
 [6,]  6   16   26   36   46  
 [7,]  7   17   27   37   47  
 [8,]  8   18   28   38   48  
 [9,]  9   19   29   39   49  
[10,] 10   20   30   40   50  

 [1] 1 0 1 0 1 0 1 0 1 0

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    11   21   31   41  
[2,] 3    13   23   33   43  
[3,] 5    15   25   35   45  
[4,] 7    17   27   37   47  
[5,] 9    19   29   39   49  

## Exercise 2: Working with vectors  (20 points)

Look at the vector below. What is its type? Convert it into numeric. Note that some values get missing due to letter `o` used instead of digit `0`. What proportion of the vector elements did we fail to convert correctly? Now let us fix this issue. Using either subsetting and assignment or `ifelse()` function replace all `NA`s in the converted numeric vector into `0` (zeros).

In [8]:
set.seed(2022)
vec <- sample(c("1", "0", "o"), size = 100, replace = TRUE)

In [9]:
# Exercise 2:

# Your code goes here

In [10]:
vec
typeof(vec)

  [1] "o" "0" "o" "o" "0" "o" "0" "o" "1" "0" "o" "1" "0" "o" "0" "1" "1" "o"
 [19] "1" "0" "0" "o" "1" "o" "0" "o" "o" "0" "1" "o" "o" "0" "o" "1" "0" "0"
 [37] "1" "o" "o" "0" "o" "1" "o" "o" "1" "0" "o" "1" "0" "1" "1" "o" "o" "0"
 [55] "1" "o" "0" "0" "o" "o" "o" "1" "0" "o" "0" "1" "o" "0" "0" "1" "1" "0"
 [73] "0" "1" "0" "o" "o" "0" "1" "o" "1" "o" "0" "o" "1" "o" "1" "o" "o" "o"
 [91] "o" "0" "0" "1" "o" "0" "1" "1" "0" "1"

[1] "character"

It is character vector.

In [11]:
vec_nu<- as.numeric(vec)

Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"

In [12]:
str(vec)
CO <- which(vec == "o")  # "o"
str(CO) 

 chr [1:100] "o" "0" "o" "o" "0" "o" "0" "o" "1" "0" "o" "1" "0" "o" "0" ...
 int [1:40] 1 3 4 6 8 11 14 18 22 24 ...


There are 40 "o" in total, accounting for 40%.

In [13]:
vec_NEW <- ifelse(vec == "o",0, vec)
vec_NEW

  [1] "0" "0" "0" "0" "0" "0" "0" "0" "1" "0" "0" "1" "0" "0" "0" "1" "1" "0"
 [19] "1" "0" "0" "0" "1" "0" "0" "0" "0" "0" "1" "0" "0" "0" "0" "1" "0" "0"
 [37] "1" "0" "0" "0" "0" "1" "0" "0" "1" "0" "0" "1" "0" "1" "1" "0" "0" "0"
 [55] "1" "0" "0" "0" "0" "0" "0" "1" "0" "0" "0" "1" "0" "0" "0" "1" "1" "0"
 [73] "0" "1" "0" "0" "0" "0" "1" "0" "1" "0" "0" "0" "1" "0" "1" "0" "0" "0"
 [91] "0" "0" "0" "1" "0" "0" "1" "1" "0" "1"

## Exercise 3: Vectorized operations  (20 points)

Using function `mean()` calculate the percentage of book titles in the vector below that have more than 10 characters in them (including whitespaces).

Tip: You can use `nchar()` function to calculate the number of characters in a vector

In [14]:
books <- c(
  "Dubliners",
  "Ulysses",
  "War and Peace",
  "Normal People",
  "Crime and Punishment",
  "The Picture of Dorian Gray"
)

In [15]:
# Exercise 3:

# Your code goes here

In [16]:
NCB <- nchar(books)
NCB 

[1]  9  7 13 13 20 26

In [17]:
NCBOT <- mean(NCB > 10)*100
NCBOT

[1] 66.66667

#There are 60 percent of book titles in the vector below that have more than 10 characters in them

## Exercise 4: Attributes and factors  (20 points)

Suppose you read in a variable which represents education of survey respondents. After consulting the codebook for this survey you determined that specific values that the variable takes are coded as follows:

- `0` - No formal education
- `1` - Primary Education
- `2` - Secondary Education
- `3` - College Education
- `4` - Post-graduate Education

Convert the variable `educ` below into a factor variable with each value coded explicitly as one of the education levels. Tabulate the variable using `table()` function. Change the order of the levels of this factor variable such that the most common education level is the first (baseline/reference) category (you can leave other education levels in their origianl order). Tabulate the variable again.   

In [18]:
set.seed(2022)
educ <- rpois(1000, 2)
educ <- ifelse(educ > 4, 4, educ)

In [19]:
# Exercise 4:

# Your code goes here

In [20]:
educ_FC <- as.factor(educ)
educ_FC

   [1] 3 2 0 2 1 2 0 0 1 3 0 1 1 2 2 0 3 2 2 3 3 2 2 1 1 4 2 4 2 3 2 2 1 1 1 0 3
  [38] 2 3 3 2 2 2 2 4 0 4 2 1 3 1 1 3 1 2 2 1 2 1 1 2 2 3 3 0 3 2 2 1 2 4 4 4 3
  [75] 2 0 2 3 2 2 1 1 3 3 0 1 0 1 2 3 1 1 2 2 1 1 0 4 2 3 4 1 3 3 2 1 4 0 2 4 3
 [112] 1 2 1 4 2 1 2 2 3 0 1 0 0 1 3 2 2 1 3 2 2 0 2 4 0 4 4 2 4 2 3 4 0 2 2 2 4
 [149] 4 2 2 4 3 4 4 4 4 0 3 3 1 3 4 1 4 2 1 4 0 0 3 1 4 1 4 1 4 1 2 0 3 1 2 2 2
 [186] 2 1 2 4 2 1 3 0 3 3 4 2 1 3 3 2 0 0 1 1 3 2 1 3 1 4 2 3 0 1 1 2 3 4 1 3 3
 [223] 1 4 0 2 1 3 2 1 0 1 2 3 2 0 3 3 1 0 1 2 3 1 0 0 1 1 4 2 1 1 0 1 4 2 0 3 4
 [260] 0 3 2 2 2 2 2 0 1 0 1 1 4 3 2 3 1 0 1 2 1 4 2 2 4 4 2 3 1 2 4 3 2 3 0 1 2
 [297] 0 1 3 3 2 2 0 2 0 2 0 1 3 2 1 2 1 1 1 2 0 3 0 0 1 2 0 1 1 1 0 2 0 2 3 0 0
 [334] 4 4 3 0 3 1 4 0 4 2 1 1 0 0 3 1 4 2 0 1 1 1 2 3 0 3 1 0 2 0 3 2 2 4 2 1 3
 [371] 1 2 2 2 4 3 3 1 1 0 3 1 4 4 1 4 2 4 1 1 1 3 2 2 4 1 2 2 2 2 2 1 2 4 0 1 1
 [408] 3 2 1 2 3 3 0 0 0 1 2 1 2 2 2 1 4 2 2 4 3 3 3 3 4 1 2 2 1 3 2 3 2 0 1 1 2
 [445] 3 3 4 3 1 0 3 1 3 2 4

In [21]:
tab_edu <- table(educ_FC) 
tab_edu

educ_FC
  0   1   2   3   4 
140 274 267 181 138 

Education coded as 2 is the most common. 

In [22]:
edu_REORDER <- factor(tab_edu, levels = c("Secondary Education", 
                                         "No formal education", 
                                         "Primary Education",
                                         "College Education", 
                                         "Post-graduate Education"))
edu_REORDER

   0    1    2    3    4 
<NA> <NA> <NA> <NA> <NA> 
5 Levels: Secondary Education No formal education ... Post-graduate Education

## Exercise 5: Conditional statements and loops  (20 points)

[Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) is a string distance metric that measures how many transformations (insertion, deletion, substitution) are required to convert one string into another. For example, consider words 'cat' and 'can'. Letter 't' in the first word can be substituted with a character 'n' in order for the two words to become identical.

For classical Levenshtein distance each of the transformations has the same cost of 1. In other words, the distance (of 1) is the same between the word pairs 'cat' - 'can' and 'cat' - 'cats'.

Below you can see two character vectors that were transformed to have a single letter as an individual element. Write a loop to compare each of the elements from one string to each of the elements from another string while keeping track of the number of transformations. Print out the result of the transformations count.

In [23]:
char_1 <- unlist(strsplit("kitten", split = ""))
char_2 <- unlist(strsplit("sitting", split = ""))

In [24]:
char_1

[1] "k" "i" "t" "t" "e" "n"

In [25]:
char_2

[1] "s" "i" "t" "t" "i" "n" "g"

In [26]:
# Exercise 5:

# Your code goes here

In [27]:
length(char_1)

char_1_mod <- append(char_1, "0") 

[1] 6

The length of char_1 is 6

In [28]:
length(char_2)

[1] 7

The length of char_2 is 7

In [29]:
char_1_mod <- append(char_1, "0")

add "0" at the end of char_1, making it the same length as char_2 

In [30]:
num_tra <- 0
num_tra  <- ifelse(char_2 == char_1_mod, num_tra, num_tra +1)

In [31]:
sum(num_tra) #  there are 3 transformations

[1] 3

There are 3 transformations